# Generated by Django 2.0.1 on 2018-02-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='dislikes',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Дизайки'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='likes',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Лайки'),
        ),
    ]
