# Generated by Django 2.0.1 on 2018-01-11 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('REST', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='Изображание магазина')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='photo',
        ),
        migrations.AddField(
            model_name='shop',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SystemUser',
        ),
        migrations.AddField(
            model_name='photo',
            name='shop',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='DonStockServer.Shop', verbose_name='Магазин'),
        ),
    ]
