# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0002_auto_20180215_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='description',
            field=models.TextField(max_length=245, null=True, verbose_name='Описание'),
        ),
    ]
