# Generated by Django 2.0.1 on 2018-01-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0003_auto_20180111_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='Название')),
                ('shop', models.ManyToManyField(related_name='Магазин', to='DonStockServer.Shop')),
            ],
        ),
    ]
