# Generated by Django 2.0.1 on 2018-01-12 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0004_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
