# Generated by Django 2.0.1 on 2018-01-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0005_auto_20180112_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='shop',
            field=models.ManyToManyField(related_name='shops', to='DonStockServer.Shop'),
        ),
    ]
