# Generated by Django 2.0.1 on 2018-01-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0006_auto_20180112_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='shop',
        ),
        migrations.AddField(
            model_name='shop',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='DonStockServer.Category', verbose_name='Категории'),
        ),
    ]
