# Generated by Django 2.0.1 on 2018-01-12 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0007_auto_20180112_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='shop',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='DonStockServer.Shop', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='link_one',
            field=models.URLField(max_length=255, null=True, verbose_name='Первая ссылка'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='link_three',
            field=models.URLField(blank=True, max_length=255, verbose_name='Третья ссылка'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='link_two',
            field=models.URLField(blank=True, max_length=255, verbose_name='Вторая ссылка'),
        ),
    ]
