# Generated by Django 2.0.1 on 2018-01-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0008_auto_20180112_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='shop',
        ),
        migrations.AddField(
            model_name='shop',
            name='photo',
            field=models.ManyToManyField(related_name='photos', to='DonStockServer.Photo', verbose_name='Фотографии'),
        ),
    ]
