# Generated by Django 2.0.1 on 2018-01-12 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0010_auto_20180112_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='shops', verbose_name='Изображание магазина'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='shop',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='DonStockServer.Shop', verbose_name='Магазин'),
        ),
    ]
