# Generated by Django 2.0.1 on 2018-01-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0012_auto_20180112_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='shops-images/%Y/%m/%d', verbose_name='Изображание магазина'),
        ),
    ]
