# Generated by Django 2.0.1 on 2018-01-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0013_auto_20180112_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='dislikes',
            field=models.PositiveIntegerField(default=0, verbose_name='Дизайки'),
        ),
        migrations.AddField(
            model_name='shop',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Лайки'),
        ),
        migrations.AddField(
            model_name='shop',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общий рейтинг'),
        ),
    ]
